<ul>
<li>Version 0.1 - 31 March 2014 Initial Release.</li>
<li>Version 0.2 - 31 March 2015
<ul>
<li>Various UI refinements</li>
<li>Extra bracket-configuration parameters</li>
<li>Plan view for round-robin brackets</li>
<li>Grouping of brackets for contemporary resource,player management</li>
<li>Work with SMSG module if available, for notification by SMS</li>
<li>Work with FrontEndUsers module if available, for unmediated recording of match results</li>
<li>Auto-scheduling of matches still TODO</li>
</ul>
</li>
</ul>
